use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use ordnung_core::fleet::{ManagedEntry, ManagedState, RelativeTo};
use ordnung_core::{
    CheckCategory, GithubSettings, Inventory, RepoConfig, Severity, TestLayoutConfig,
    check_definitions, language_profile,
};

pub const START_MARKER: &str = "<!-- ordnung:instructions:start -->";
pub const END_MARKER: &str = "<!-- ordnung:instructions:end -->";

pub struct InstructionContext<'a> {
    pub inventory: &'a Inventory,
    pub policy: &'a BTreeMap<String, Severity>,
    pub github: &'a GithubSettings,
    pub test_layout: &'a TestLayoutConfig,
    pub local: &'a RepoConfig,
    pub fleet_name: Option<&'a str>,
    pub managed: &'a [&'a ManagedEntry],
}

pub fn render(context: &InstructionContext<'_>) -> String {
    let mut output = String::new();
    writeln!(output, "{START_MARKER}").unwrap();
    writeln!(output, "## Ordnung Repository Rules").unwrap();
    writeln!(
        output,
        "This block is generated by `ordnung instructions`; refresh it instead of editing it by hand."
    )
    .unwrap();

    if let Some(fleet_name) = context.fleet_name {
        writeln!(
            output,
            "- Policy source: fleet `{fleet_name}` plus explicit local overrides."
        )
        .unwrap();
    } else {
        writeln!(
            output,
            "- Policy source: this repository's `ordnung.toml` and defaults."
        )
        .unwrap();
    }

    let languages = collect_inventory_values(context.inventory, |project| {
        project.languages.iter().map(ToString::to_string).collect()
    });
    let ecosystems = collect_inventory_values(context.inventory, |project| {
        project.ecosystems.iter().map(ToString::to_string).collect()
    });
    let capabilities = collect_inventory_values(context.inventory, |project| {
        project
            .capabilities
            .iter()
            .map(ToString::to_string)
            .collect()
    });
    let mut detected = Vec::new();
    push_named_values(&mut detected, "languages", &languages);
    push_named_values(&mut detected, "ecosystems", &ecosystems);
    push_named_values(&mut detected, "capabilities", &capabilities);
    if !detected.is_empty() {
        writeln!(output, "- Detected: {}.", detected.join("; ")).unwrap();
    }
    writeln!(
        output,
        "Treat required rules as constraints on every change. Recommended rules should be preserved or improved when the touched area makes that practical. Each rule is labeled with its exact Ordnung configuration key."
    )
    .unwrap();
    writeln!(
        output,
        "Configured rules describe the target repository state; some roadmap rules may not yet be mechanically enforced."
    )
    .unwrap();
    render_rules(
        &mut output,
        context.policy,
        Severity::Required,
        "Required rules",
    );
    render_rules(
        &mut output,
        context.policy,
        Severity::Recommended,
        "Recommended rules",
    );

    writeln!(output, "\n### Repository-specific settings").unwrap();

    if !context.local.ignore.is_empty() {
        writeln!(
            output,
            "- Ordnung ignores: `{}`.",
            context.local.ignore.join("`, `")
        )
        .unwrap();
    }

    render_test_layout(&mut output, context);
    render_scripts(&mut output, context);
    render_corrals(&mut output, context);
    render_codegen(&mut output, context.local);
    render_github_settings(&mut output, context.github);
    render_overrides(&mut output, context.local);
    render_managed(&mut output, context.managed);

    writeln!(
        output,
        "- Before finishing structural work, run `ordnung check .` and resolve required findings."
    )
    .unwrap();
    write!(output, "{END_MARKER}").unwrap();
    output
}

fn render_corrals(output: &mut String, context: &InstructionContext<'_>) {
    if context.policy.get("stray-files") == Some(&Severity::Off) {
        return;
    }
    writeln!(
        output,
        "- Working notes belong under `{}`.",
        context.local.stray_files.notes.display()
    )
    .unwrap();
    if !context.local.stray_files.allow.is_empty() {
        writeln!(
            output,
            "- Allowed root text files: `{}`.",
            context
                .local
                .stray_files
                .allow
                .iter()
                .map(|path| path.display().to_string())
                .collect::<Vec<_>>()
                .join("`, `")
        )
        .unwrap();
    }
}

fn render_scripts(output: &mut String, context: &InstructionContext<'_>) {
    if context.policy.get("scripts") == Some(&Severity::Off) {
        return;
    }
    let config = &context.local.scripts;
    writeln!(
        output,
        "- Shell scripts: keep them under `{}`; development entry `{}` must be named in the root README.",
        config.directory.display(),
        config.development_path().display()
    )
    .unwrap();
    if !config.allow.is_empty() {
        writeln!(
            output,
            "- Shell-script path exceptions: `{}`.",
            config
                .allow
                .iter()
                .map(|path| path.display().to_string())
                .collect::<Vec<_>>()
                .join("`, `")
        )
        .unwrap();
    }
}

fn render_codegen(output: &mut String, local: &RepoConfig) {
    for generator in &local.codegen {
        let root = if generator.scope_root().as_os_str().is_empty() {
            ".".to_owned()
        } else {
            generator.scope_root().display().to_string()
        };
        writeln!(
            output,
            "- Codegen `{}` at `{root}`: run `{}`; committed outputs `{}`.",
            generator.name,
            generator.command,
            generator.outputs.join("`, `")
        )
        .unwrap();
    }
}

pub fn inject(existing: &str, generated: &str) -> Result<String, String> {
    let starts = existing.match_indices(START_MARKER).collect::<Vec<_>>();
    let ends = existing.match_indices(END_MARKER).collect::<Vec<_>>();
    match (starts.as_slice(), ends.as_slice()) {
        ([], []) => {
            let mut updated = existing.to_owned();
            if !updated.is_empty() {
                if !updated.ends_with('\n') {
                    updated.push('\n');
                }
                updated.push('\n');
            }
            updated.push_str(generated);
            updated.push('\n');
            Ok(updated)
        }
        ([(start, _)], [(end, _)]) if start < end => {
            let after = end + END_MARKER.len();
            let mut updated = String::with_capacity(existing.len() + generated.len());
            updated.push_str(&existing[..*start]);
            updated.push_str(generated);
            updated.push_str(&existing[after..]);
            Ok(updated)
        }
        _ => Err("instruction file has malformed or duplicate Ordnung markers".into()),
    }
}

fn collect_inventory_values(
    inventory: &Inventory,
    values: impl Fn(&ordnung_core::Project) -> BTreeSet<String>,
) -> BTreeSet<String> {
    inventory.projects.iter().flat_map(values).collect()
}

fn push_named_values(output: &mut Vec<String>, label: &str, values: &BTreeSet<String>) {
    if !values.is_empty() {
        output.push(format!(
            "{label} `{}`",
            values.iter().cloned().collect::<Vec<_>>().join("`, `")
        ));
    }
}

fn render_rules(
    output: &mut String,
    policy: &BTreeMap<String, Severity>,
    severity: Severity,
    heading: &str,
) {
    if !policy.values().any(|configured| *configured == severity) {
        return;
    }
    writeln!(output, "\n### {heading}").unwrap();
    let mut described = BTreeSet::new();
    for category in CheckCategory::ALL {
        let definitions = check_definitions()
            .iter()
            .filter(|definition| {
                definition.category == category && policy.get(definition.id) == Some(&severity)
            })
            .collect::<Vec<_>>();
        if definitions.is_empty() {
            continue;
        }
        writeln!(output, "- **{}**", category.display_name()).unwrap();
        for definition in definitions {
            described.insert(definition.id);
            writeln!(
                output,
                "  - `{}`: {}",
                definition.id, definition.instructions
            )
            .unwrap();
        }
    }
    let unknown = policy
        .iter()
        .filter_map(|(check, configured)| {
            (*configured == severity && !described.contains(check.as_str()))
                .then_some(check.as_str())
        })
        .collect::<Vec<_>>();
    if !unknown.is_empty() {
        writeln!(
            output,
            "- **Other configured rules** (`{}`): Follow their Ordnung policy definitions.",
            unknown.join("`, `")
        )
        .unwrap();
    }
}

fn render_test_layout(output: &mut String, context: &InstructionContext<'_>) {
    if context.policy.get("test-layout") == Some(&Severity::Off) {
        return;
    }
    for language in context
        .inventory
        .projects
        .iter()
        .flat_map(|project| &project.languages)
        .collect::<BTreeSet<_>>()
    {
        let Some(profile) = language_profile(language.as_str()) else {
            continue;
        };
        let applies = context.inventory.projects.iter().any(|project| {
            project.has_language(profile.id)
                && !project.languages.iter().any(|candidate| {
                    language_profile(candidate.as_str())
                        .is_some_and(|candidate_profile| candidate_profile.supersedes(profile))
                })
        });
        if !applies {
            continue;
        }
        let layout = context.test_layout.layout_for(profile);
        let roots = layout
            .source_roots
            .iter()
            .map(|path| path.display().to_string())
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            output,
            "- {} tests: source roots `{roots}`; external tests under `{}`; inline scan {}; mirrored files {}.",
            profile.display_name,
            layout.test_root.display(),
            enabled(context.test_layout.scan_inline),
            enabled(context.test_layout.require_mirror)
        )
        .unwrap();
    }
}

fn render_github_settings(output: &mut String, settings: &GithubSettings) {
    let mut configured = Vec::new();
    if let Some(value) = settings.allow_auto_merge {
        configured.push(format!("allow auto-merge: {value}"));
    }
    if let Some(value) = settings.delete_branch_on_merge {
        configured.push(format!("delete branch on merge: {value}"));
    }
    if let Some(value) = settings.allow_update_branch {
        configured.push(format!("allow update branch: {value}"));
    }
    if !configured.is_empty() {
        writeln!(output, "- GitHub settings: {}.", configured.join("; ")).unwrap();
    }
}

fn render_overrides(output: &mut String, local: &RepoConfig) {
    for (check, exception) in &local.overrides {
        writeln!(
            output,
            "- Approved check exception: `{check}` is {} because {}.",
            severity_name(exception.severity),
            exception.reason.trim_end_matches('.')
        )
        .unwrap();
    }
    for (name, exception) in [
        (
            "allow auto-merge",
            local.github_overrides.allow_auto_merge.as_ref(),
        ),
        (
            "delete branch on merge",
            local.github_overrides.delete_branch_on_merge.as_ref(),
        ),
        (
            "allow update branch",
            local.github_overrides.allow_update_branch.as_ref(),
        ),
    ] {
        if let Some(exception) = exception {
            writeln!(
                output,
                "- Approved GitHub exception: {name} is {} because {}.",
                exception.value,
                exception.reason.trim_end_matches('.')
            )
            .unwrap();
        }
    }
}

fn render_managed(output: &mut String, managed: &[&ManagedEntry]) {
    if managed.is_empty() {
        return;
    }
    let descriptions = managed
        .iter()
        .map(|entry| {
            let state = match entry.state {
                ManagedState::Present => "present",
                ManagedState::Absent => "absent",
            };
            let scope = match entry.relative_to {
                RelativeTo::Repo => "at repository root".to_owned(),
                RelativeTo::Project => match &entry.when {
                    Some(selector) => format!("per matching project ({selector})"),
                    None => "per matching project".to_owned(),
                },
            };
            format!("`{}` {state} {scope}", entry.destination.display())
        })
        .collect::<Vec<_>>();
    writeln!(
        output,
        "- Fleet-owned paths (change the fleet source, not local copies): {}.",
        descriptions.join("; ")
    )
    .unwrap();
}

fn severity_name(severity: Severity) -> &'static str {
    match severity {
        Severity::Required => "required",
        Severity::Recommended => "recommended",
        Severity::Off => "disabled",
    }
}

fn enabled(value: bool) -> &'static str {
    if value { "enabled" } else { "disabled" }
}
